import csv
import io
from datetime import UTC, datetime
from typing import Any

from app.schemas.report import RiskReport, STRDraft
from app.schemas.signals import RiskAssessment


def generate_str_draft(
    assessment: RiskAssessment, transaction: Any | None = None
) -> STRDraft | None:
    """
    Generates a deterministic STR-ready draft ONLY for HIGH (61-80) and CRITICAL (81-100).
    Returns None for Very Low, Low, and Medium transactions.
    """
    if assessment.risk_band not in ("High", "Critical") and assessment.consolidated_score < 61.0:
        return None

    tx_id = assessment.transaction_id
    str_id = f"STR-{tx_id}"
    now_str = datetime.now(UTC).isoformat()

    acc_id = getattr(transaction, "account_id", "UNKNOWN")
    rec_id = getattr(transaction, "recipient_id", "UNKNOWN")
    amt = float(getattr(transaction, "amount", 0.0))
    curr = str(getattr(transaction, "currency", "USD"))

    triggered_names = [f"{f.signal_id} ({f.name})" for f in assessment.triggered_signals]
    triggered_str = ", ".join(triggered_names) if triggered_names else "Multiple anomaly factors"

    summary = (
        f"[DRAFT] Suspicious Transaction Report for Transaction {tx_id}. "
        f"Consolidated Risk Score: {assessment.consolidated_score:.1f}/100 "
        f"({assessment.risk_band} Band). "
        f"Recommended Action: {assessment.recommended_action}. {assessment.explanation}"
    )

    subs = (
        f"Adaptive Friction={assessment.af_subscore:.1f}, "
        f"Fund Flow={assessment.ff_subscore:.1f}, "
        f"Phishing={assessment.ph_subscore:.1f}"
    )

    narrative_lines = [
        f"=== SUSPICIOUS TRANSACTION REPORT DRAFT ({assessment.risk_band.upper()} RISK) ===",
        f"FILING DRAFT ID: {str_id}",
        f"GENERATION TIMESTAMP: {now_str}",
        "STATUS: DRAFT (UNFILED)",
        "",
        "1. SUBJECT & TRANSACTION IDENTIFIERS:",
        f"   - Transaction Reference ID: {tx_id}",
        f"   - Sender / Originating Account ID: {acc_id}",
        f"   - Beneficiary / Recipient Account ID: {rec_id}",
        f"   - Transaction Value: {amt:.2f} {curr}",
        "",
        "2. COMPOSITE RISK ASSESSMENT & SCORES:",
        f"   - Consolidated Risk Score: {assessment.consolidated_score:.2f} / 100",
        f"   - Risk Classification Band: {assessment.risk_band}",
        f"   - Recommended Automated Action: {assessment.recommended_action}",
        f"   - Signal Subscores: {subs}",
        "",
        "3. DETAILED ANOMALY NARRATIVE & EVIDENCE:",
        f"   - Deterministic Summary: {assessment.explanation}",
        f"   - Triggered Risk Factors: {triggered_str}.",
        "",
        "4. REGULATORY DISCLAIMER & NOTICE:",
        "   THIS IS AN AUTOMATED COMPLIANCE DRAFT GENERATED BY FRAUDFUSION RISK ENGINE. "
        "THIS DOCUMENT CONSTITUTES A PRELIMINARY SUSPICIOUS TRANSACTION REPORT (STR) DRAFT "
        "REQUIRING REVIEW AND AUTHORIZATION BY A COMPLIANCE OFFICER PRIOR TO FILING.",
    ]

    return STRDraft(
        str_id=str_id,
        transaction_id=tx_id,
        status="DRAFT",
        filing_type="SUSPICIOUS_TRANSACTION_REPORT",
        generated_at=now_str,
        summary_of_suspicion=summary,
        narrative="\n".join(narrative_lines),
        subject_identifiers={"account_id": acc_id, "recipient_id": rec_id},
        transaction_details={
            "transaction_id": tx_id,
            "amount": amt,
            "currency": curr,
        },
        risk_metrics={
            "consolidated_score": assessment.consolidated_score,
            "risk_band": assessment.risk_band,
            "recommended_action": assessment.recommended_action,
            "af_subscore": assessment.af_subscore,
            "ff_subscore": assessment.ff_subscore,
            "ph_subscore": assessment.ph_subscore,
        },
    )


def generate_risk_report(
    assessment: RiskAssessment, transaction: Any | None = None
) -> RiskReport:
    """Converts a completed RiskAssessment into a comprehensive RiskReport."""
    tx_id = assessment.transaction_id
    report_id = f"RPT-{tx_id}"

    acc_id = getattr(transaction, "account_id", "UNKNOWN")
    rec_id = getattr(transaction, "recipient_id", "UNKNOWN")
    amt = float(getattr(transaction, "amount", 0.0))
    curr = str(getattr(transaction, "currency", "USD"))
    chan = str(getattr(transaction, "channel", "WEB"))
    pm = str(getattr(transaction, "payment_method", "CREDIT_CARD"))

    str_draft = generate_str_draft(assessment, transaction)
    str_status = "DRAFT_GENERATED" if str_draft else "NOT_REQUIRED"

    evidence: dict[str, Any] = {}
    if transaction:
        dev_ctx = getattr(transaction, "device_context", None)
        if dev_ctx:
            evidence["device_context"] = (
                dev_ctx.model_dump() if hasattr(dev_ctx, "model_dump") else str(dev_ctx)
            )
        src_meta = getattr(transaction, "source_metadata", None)
        if src_meta:
            evidence["source_metadata"] = src_meta

    return RiskReport(
        report_id=report_id,
        transaction_id=tx_id,
        account_id=acc_id,
        recipient_id=rec_id,
        amount=amt,
        currency=curr,
        channel=chan,
        payment_method=pm,
        consolidated_score=assessment.consolidated_score,
        risk_band=assessment.risk_band,
        recommended_action=assessment.recommended_action,
        af_subscore=assessment.af_subscore,
        ff_subscore=assessment.ff_subscore,
        ph_subscore=assessment.ph_subscore,
        triggered_signals=assessment.triggered_signals,
        explanation=assessment.explanation,
        all_signal_results=assessment.all_signal_results,
        supporting_evidence=evidence,
        str_status=str_status,
        str_draft=str_draft,
    )


def export_report_to_json(report: RiskReport) -> str:
    """Exports RiskReport as a pretty-printed JSON string."""
    return report.model_dump_json(indent=2)


def export_report_to_csv(report: RiskReport) -> str:
    """Exports RiskReport high-level summary as a CSV string."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "transaction_id",
        "timestamp",
        "account_id",
        "recipient_id",
        "amount",
        "currency",
        "consolidated_score",
        "risk_band",
        "recommended_action",
        "af_subscore",
        "ff_subscore",
        "ph_subscore",
        "str_status",
        "explanation",
    ])
    writer.writerow([
        report.transaction_id,
        report.timestamp,
        report.account_id,
        report.recipient_id,
        f"{report.amount:.2f}",
        report.currency,
        f"{report.consolidated_score:.2f}",
        report.risk_band,
        report.recommended_action,
        f"{report.af_subscore:.2f}",
        f"{report.ff_subscore:.2f}",
        f"{report.ph_subscore:.2f}",
        report.str_status,
        report.explanation,
    ])
    return output.getvalue()


def export_report_to_html(report: RiskReport) -> str:
    """Exports RiskReport as a standalone, styled HTML document."""
    triggered_html = ""
    if report.triggered_signals:
        rows = "".join([
            f"<tr><td><code>{f.signal_id}</code></td>"
            f"<td><strong>{f.name}</strong></td>"
            f"<td>{f.risk_factor:.2f}</td>"
            f"<td>{f.explanation}</td></tr>"
            for f in report.triggered_signals
        ])
        triggered_html = (
            "<h3>Triggered Risk Signals</h3>"
            "<table class='data-table'>"
            "<thead><tr><th>Signal Code</th><th>Factor Name</th>"
            "<th>Risk Factor</th><th>Explanation</th></tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )

    str_section_html = ""
    if report.str_draft:
        str_section_html = (
            "<div class='str-banner'>"
            "<h3>🚨 SUSPICIOUS TRANSACTION REPORT DRAFT</h3>"
            f"<p><strong>STR ID:</strong> {report.str_draft.str_id} | "
            f"<strong>Status:</strong> {report.str_draft.status}</p>"
            f"<pre>{report.str_draft.narrative}</pre>"
            "</div>"
        )

    css_style = (
        "body { font-family: sans-serif; margin: 2rem; color: #1e293b; background: #f8fafc; }\n"
        ".card { background: #ffffff; padding: 2rem; border-radius: 8px; "
        "border: 1px solid #e2e8f0; max-width: 900px; margin: auto; }\n"
        ".header { border-bottom: 2px solid #0f172a; padding-bottom: 1rem; "
        "margin-bottom: 1.5rem; display: flex; justify-content: space-between; }\n"
        ".score-badge { font-size: 2rem; font-weight: 800; padding: 0.5rem 1rem; "
        "border-radius: 6px; background: #f1f5f9; border: 2px solid #334155; }\n"
        ".grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; "
        "margin: 1.5rem 0; }\n"
        ".metric-box { background: #f8fafc; padding: 1rem; border-radius: 6px; "
        "border: 1px solid #e2e8f0; }\n"
        ".data-table { width: 100%; border-collapse: collapse; margin-top: 1rem; }\n"
        ".data-table th, .data-table td { border: 1px solid #cbd5e1; padding: 0.6rem; "
        "text-align: left; font-size: 0.85rem; }\n"
        ".data-table th { background: #f1f5f9; }\n"
        ".str-banner { background: #fef2f2; border: 2px dashed #ef4444; "
        "border-radius: 6px; padding: 1.25rem; margin-top: 1.5rem; color: #991b1b; }\n"
        "pre { font-family: monospace; white-space: pre-wrap; font-size: 0.85rem; }\n"
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>FraudFusion Risk Report - {report.transaction_id}</title>
  <style>
    {css_style}
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <div>
        <h1 style="margin:0; font-size:1.5rem;">FraudFusion Risk Assessment Report</h1>
        <p style="margin:0.25rem 0 0 0; color:#64748b;">
          Transaction: <strong>{report.transaction_id}</strong> | Timestamp: {report.timestamp}
        </p>
      </div>
      <div class="score-badge">
        {report.consolidated_score:.0f} / 100
      </div>
    </div>

    <div>
      <p>
        <strong>Risk Band:</strong> {report.risk_band} |
        <strong>Action:</strong> {report.recommended_action} |
        <strong>STR Status:</strong> {report.str_status}
      </p>
      <p><strong>Explanation:</strong> {report.explanation}</p>
    </div>

    <div class="grid">
      <div class="metric-box">
        <strong>Adaptive Friction (AF)</strong>
        <div style="font-size:1.25rem; font-weight:700;">{report.af_subscore:.1f} / 100</div>
        <small style="color:#64748b;">Weight: 45%</small>
      </div>
      <div class="metric-box">
        <strong>Fund Flow (FF)</strong>
        <div style="font-size:1.25rem; font-weight:700;">{report.ff_subscore:.1f} / 100</div>
        <small style="color:#64748b;">Weight: 35%</small>
      </div>
      <div class="metric-box">
        <strong>Phishing (PH)</strong>
        <div style="font-size:1.25rem; font-weight:700;">{report.ph_subscore:.1f} / 100</div>
        <small style="color:#64748b;">Weight: 20%</small>
      </div>
    </div>

    <h3>Transaction & Subject Identifiers</h3>
    <table class="data-table">
      <tr>
        <th>Account / Sender ID</th><td>{report.account_id}</td>
        <th>Beneficiary / Recipient ID</th><td>{report.recipient_id}</td>
      </tr>
      <tr>
        <th>Transaction Amount</th><td>{report.amount:.2f} {report.currency}</td>
        <th>Channel & Method</th><td>{report.channel} / {report.payment_method}</td>
      </tr>
    </table>

    {triggered_html}
    {str_section_html}
  </div>
</body>
</html>
"""
