from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from app.schemas.signals import SignalFactor, SignalGroupResult


class STRDraft(BaseModel):
    str_id: str = Field(..., description="Unique STR draft identifier e.g. STR-TX-1001")
    transaction_id: str = Field(..., description="Target transaction identifier")
    status: str = Field(default="DRAFT", description="Label clearly marking status as DRAFT")
    filing_type: str = Field(
        default="SUSPICIOUS_TRANSACTION_REPORT",
        description="Filing category e.g. STR / AML Alert",
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(),
        description="Timestamp of STR draft generation",
    )
    summary_of_suspicion: str = Field(
        ..., description="Executive summary detailing primary fraud drivers"
    )
    narrative: str = Field(
        ..., description="Full regulatory narrative text describing anomalies and signals"
    )
    subject_identifiers: dict[str, Any] = Field(
        default_factory=dict, description="Parties and account identifiers"
    )
    transaction_details: dict[str, Any] = Field(
        default_factory=dict, description="Amount, currency, channel, timestamp details"
    )
    risk_metrics: dict[str, Any] = Field(
        default_factory=dict,
        description="Consolidated risk score, risk band, action, and subscores",
    )
    regulatory_notes: str = Field(
        default=(
            "AUTOMATED DRAFT GENERATED BY FRAUDFUSION RISK ENGINE - "
            "REQUIRES COMPLIANCE OFFICER REVIEW PRIOR TO FILING."
        ),
        description="Regulatory disclaimer notice",
    )



class RiskReport(BaseModel):
    report_id: str = Field(..., description="Unique report identifier e.g. RPT-TX-1001")
    transaction_id: str = Field(..., description="Transaction ID evaluated")
    timestamp: str = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(),
        description="Transaction or evaluation timestamp",
    )
    account_id: str = Field(default="UNKNOWN", description="Sender or account ID")
    recipient_id: str = Field(default="UNKNOWN", description="Recipient or beneficiary ID")
    amount: float = Field(default=0.0, description="Transaction amount")
    currency: str = Field(default="USD", description="Currency code")
    channel: str = Field(default="WEB", description="Channel e.g. WEB, MOBILE_APP")
    payment_method: str = Field(
        default="CREDIT_CARD", description="Payment method e.g. WIRE_TRANSFER"
    )
    consolidated_score: float = Field(..., ge=0.0, le=100.0, description="Final score 0-100")
    risk_band: str = Field(..., description="Very Low, Low, Medium, High, or Critical")
    recommended_action: str = Field(
        ..., description="ALLOW, MONITOR, CHALLENGE, HOLD, or BLOCK_AND_REPORT"
    )
    af_subscore: float = Field(default=0.0, ge=0.0, le=100.0)
    ff_subscore: float = Field(default=0.0, ge=0.0, le=100.0)
    ph_subscore: float = Field(default=0.0, ge=0.0, le=100.0)
    triggered_signals: list[SignalFactor] = Field(
        default_factory=list, description="Factors with risk_factor > 0"
    )
    explanation: str = Field(..., description="Concise explainability summary")
    all_signal_results: dict[str, SignalGroupResult] = Field(
        default_factory=dict, description="Detailed AF, FF, PH group results"
    )
    supporting_evidence: dict[str, Any] = Field(
        default_factory=dict, description="Raw input metrics, device context, and parameters"
    )
    str_status: str = Field(
        default="NOT_REQUIRED",
        description="STR status: 'NOT_REQUIRED' or 'DRAFT_GENERATED'",
    )
    str_draft: STRDraft | None = Field(
        default=None, description="STR draft object if score >= 61 or High/Critical band"
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(),
        description="Report generation timestamp",
    )
